### ISSUE TITLE
The plugin doesn't compile JSP using the POM dependencies

### ISSUE THREAD

**Issue by OpenPj** [Jasig/jspc-maven-plugin#23]
Trying to compile some JSP with import declaration related to classes included as Maven dependencies it returns a compilation error:

An error occurred at line: 39 in the jsp file: /jsp/search.jsp
[ERROR] DropDownManager cannot be resolved

But the DropDownManager is included as one of the dependencies in the current WAR project where I have declated the plugin. 

This is a multi module Maven project where the WAR is one of the modules.

How can I add these dependencies for compiling JSP?

**Comment by HeadOnAPlate** [comment]
We are having the same issue. Any info on this issue?

**Comment by HeadOnAPlate** [comment]
I traced it to a paths mismatch between the generated jarfile containing the module dependencies and the way the JspCompiler resolves .tld files.
This PR should fix the issue.
