### ISSUE TITLE
/META-INF/resources

### ISSUE THREAD

**Issue by mikeya** [Jasig/jspc-maven-plugin#26]
Doesn't seem to be finding jsps exposed in jars via META-INF/resources

**Comment by HeadOnAPlate** [comment]
If you do not specify a sources parameter, the plugin seems to exclude the following source directories by default: 
```java
sources.setExcludes(Arrays.asList("WEB-INF/web.xml", "META-INF/**"));
```

**Comment by ChristianMurphy** [comment]
@mikeya as @HeadOnAPlate mentioned these files are ignored unless explicitly included in the sources.
