### ISSUE TITLE
Fail to compile JSPs that use custom taglibs

### ISSUE THREAD

**Issue by honeyAndSw** [Jasig/jspc-maven-plugin#30]
Hi,

My web application have several custom taglib and the plugin fails to compile JSP files that use those taglib.

The error log looks like:
```
The absolute uri: {my custom taglib name shows here} cannot be resolved in either web.xml or the jar files deployed with this application
```

And web.xml file taglib configuration looks like:
```
<web-app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         version="2.5"
         xmlns="http://java.sun.com/xml/ns/javaee"
		 xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd">
	<jsp-config> 
		<taglib> 
			<taglib-uri>{some uri}</taglib-uri>
			 <taglib-location>{tld file location e.g /WEB-INF/tld/...}</taglib-location> 
		</taglib>
                <!-- few more <taglib></taglib> comes here -->
	</jsp-config>
</web-app>
```

It uses tomcat6, and I uses tomcat6 compiler plugin as well.

I'm looking forward to your answer!
Thanks for the awesome plugin :)

**Comment by GregDThomas** [comment]
This normally means that you've forgotten to copy the TLD file (or the JAR containing it) to the WEB-INF/lib folder. It's not enough for it to be in the class path.

**Comment by honeyAndSw** [comment]
@GregDThomas Thanks for the comment.

So you mean the directory structure should look like this? :
```
WEB-INF/
   lib/
      tld/
```
Cause current structure is:
```
WEB-INF/
   tld/
```
and I played with this plugin so many times but couldn't solve the problem in the end. :(
I returned to the original **org.codehaus.mojo** plugin and finally everything works fine.

**Comment by GregDThomas** [comment]
If your tld file is `mytaglib.tld`, then I'd expect it to be

    WEB-INF/mytaglib.tld

If your tld file is contained in a `mytaglibs.jar`, I'd expect that JAR file to be

    WEB-INF/lib/mytaglibs.jar

**Comment by jameswennmacher** [comment]
I believe on newer versions of Tomcat (8?), TLDs can be placed just about anywhere other than WEB-INF/tags.  One of the uPortal developers recently moved tlds around with a comment 'JSP spec 7.3.1 states TLDs must not be placed inside /WEB-INF/tags'.  I haven't looked into this, but I do know we have tld files in WEB-INF and some other folders and it does work fine.

**Comment by honeyAndSw** [comment]
@GregDThomas But the tricky point is, when I try org.codehaus.mojo plugin tomcat6 compiler, everything's good when TLDss are not in WEB-INF:
```
src/main/resources/tld/
```
So I guess this is not the problem of where tld files are.

@jameswennmacher yup, I also believe TLD files shouldn't have to be in WEB-INF.

**Comment by bjagg** [comment]
Yes, Tomcat 8 enforces the spec that TLDs cannot be in WEB-INF/tags/
(except the "implicit.tld")...

    JSP.7.3.1 Identifying Tag Library Descriptors
    Tag library descriptor files have names that use the extension .tld,
    and the
    extension indicates a tag library descriptor file. When deployed
    inside a JAR file,
    the tag library descriptor files must be in the META-INF directory,
    or a subdirectory
    of it. When deployed directly into a web application, the tag
    library descriptor
    files must always be in the WEB-INF directory, or some subdirectory
    of it. TLD
    files should not be placed in /WEB-INF/classes or /WEB-INF/lib, and
    must not be
    placed inside /WEB-INF/tags or a subdirectory of it, unless named
    implicit.tld and
    intended to configure an implicit tag library with its JSP version
    and tlib-version.


Tomcat 7 ignores misplaced TLD files while Tomcat 8 throws errors. I do
not recall an issue with Tomcat 6 though.

I would suggest placing TLD files in /WEB-INF/tlds/ .

Best,
Benito

**Comment by jameswennmacher** [comment]
To clarify my previous comment, we have tlds in WEB-INF and WEB-INF/* (but not WEB-INF/tags).

**Comment by honeyAndSw** [comment]
@bjagg @jameswennmacher Thanks alot! :)
