### ISSUE TITLE
ServletException on latest Tomcat 8 versions

### ISSUE THREAD

**Issue by HaraldWalker** [Jasig/jspc-maven-plugin#32]
Using the jspc-compiler-tomcat8 2.0.2 causes ServletException when trying to run it on latest Tomcat version (e.g. 8.0.36). Version 2.0.2 uses Tomcat 8.0.15.

javax.servlet.ServletException: java.lang.NoSuchMethodError: org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate(Ljava/lang/String;Ljava/lang/Class;Ljavax/servlet/jsp/PageContext;Lorg/apache/jasper/runtime/ProtectedFunctionMapper;Z)Ljava/lang/Object;
    org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:909)

Fix: Update Tomcat version being used for for compiler.

**Comment by sleroy** [comment]
Any help required ?

**Comment by ChristianMurphy** [comment]
resolved in #33
