### ISSUE TITLE
How to exclude sources from compiler?

### ISSUE THREAD

**Issue by 40rn05lyv** [Jasig/jspc-maven-plugin#34]
Hi, I have a project with hundreds of jsp pages. Most of them can be compiled, but there are about 20 that are included in other JSP pages, and, therefore, can't be compiled.

 I know, that there is `sources` parameter in `jspc-maven-plugin`, but it's very inconvenient to use it in my situation. Is there `exclude` parameter or something like this?

**Comment by GregDThomas** [comment]
It's normal to use a .jspf extension for fragments of JSP files (http://filext.com/file-extension/JSPF) - the jspc won't attempt to compile those.

So you can probably just rename them.

**Comment by 40rn05lyv** [comment]
Thanks. I also found out that `<sources>` has actually `<exclude>` parameter (it can be used as temporary workaround before switching to jspf):

```
<sources>
  <directory>${project.basedir}/src/main/webapp</directory>
  <exclude>myjsp.jsp</exclude>
</sources>
```
