### ISSUE TITLE
Can this plugin run in a forked jvm?

### ISSUE THREAD

**Issue by benze** [Jasig/jspc-maven-plugin#37]
I'm having some significant memory issues when using this plugin.  I have to boost my max mem settings to 2G and heap space to 512 just to compile my JSPs within the context of my maven build.

Is there a way to run this in a forked jvm to reduce the memory footprint?

Is there a reason why it consumes so much memory?  Is there a way to track down why/where the memory is being used?  Is there be a memory leak somewhere?

**Comment by ChristianMurphy** [comment]
> Is there a way to run this in a forked jvm to reduce the memory footprint?

Creating a forked process in the JVM would increase overall memory usage.

> Is there a way to track down why/where the memory is being used?

Sure, a [Java Profiler](https://www.google.com/?q=java+profiler) could track down memory usage.

**Comment by ChristianMurphy** [comment]
@benze without profiling information, there isn't much to go off for resolving the issue you are experiencing.
I'm going to close this issue for now, please post back on this issue or open a new issue when you have a chance to capture the profiling information.
