### ISSUE TITLE
how to use in spring mvc

### ISSUE THREAD

**Issue by damozhiying** [Jasig/jspc-maven-plugin#45]
how to use in spring mvc

**Comment by ChristianMurphy** [comment]
Hi @damozhiying! 👋 
`jspc-maven-plugin` can be included as part of the maven build process for the Spring MVC application.
There is more information in the [usage guide](http://developer.jasig.org/projects/jspc-maven-plugin/2.0.0/jspc-maven-plugin/usage.html) on the Wiki. 📝
