### ISSUE TITLE
No implementation for org.codehaus.mojo.jspc.compiler.JspCompilerFactory was bound

### ISSUE THREAD

**Issue by jimshowalter** [Jasig/jspc-maven-plugin#48]
From the documentation, added this to the pom:

      <plugin>
        <groupId>org.jasig.mojo.jspc</groupId>
        <artifactId>jspc-maven-plugin</artifactId>
        <version>2.0.0</version>
        <configuration>
          <includeInProject>false</includeInProject>
        </configuration>
      </plugin>

Executed:

mvn jspc:compile

Got error:

[ERROR] Failed to execute goal org.jasig.mojo.jspc:jspc-maven-plugin:2.0.0:compile (default-cli) on project webapps-qbo: Execution default-cli of goal org.jasig.mojo.jspc:jspc-maven-plugin:2.0.0:compile failed: Unable to load the mojo 'compile' (or one of its required components) from the plugin 'org.jasig.mojo.jspc:jspc-maven-plugin:2.0.0': com.google.inject.ProvisionException: Unable to provision, see the following errors:
[ERROR]
[ERROR] 1) No implementation for org.codehaus.mojo.jspc.compiler.JspCompilerFactory was bound.
[ERROR] while locating org.codehaus.mojo.jspc.CompileMojo
[ERROR] at ClassRealm[plugin>org.jasig.mojo.jspc:jspc-maven-plugin:2.0.0, parent: sun.misc.Launcher$AppClassLoader@55f96302] (via modules: org.eclipse.sisu.wire.WireModule -> org.eclipse.sisu.plexus.PlexusBindingModule)
[ERROR] while locating org.apache.maven.plugin.Mojo annotated with @com.google.inject.name.Named(value=org.jasig.mojo.jspc:jspc-maven-plugin:2.0.0:compile)

What am I missing?

**Comment by ChristianMurphy** [comment]
@jimshowalter Do you have a `jspc-compiler-{{tomcat version}}` dependency included in the plugin element?

ref: http://developer.jasig.org/projects/jspc-maven-plugin/2.0.0/jspc-maven-plugin/usage.html

``` diff
<plugin>
  <groupId>org.jasig.mojo.jspc</groupId>
  <artifactId>jspc-maven-plugin</artifactId>
  <version>2.0.0</version>
  <configuration>
    <includeInProject>false</includeInProject>
  </configuration>
+ <dependencies>
+     <dependency>
+         <groupId>org.jasig.mojo.jspc</groupId>
+         <artifactId>jspc-compiler-tomcat7</artifactId>
+     </dependency>
+ </dependencies>
</plugin>
```

**Comment by jimshowalter** [comment]
Ah, my bad. Because we're not building a WAR, I skipped the entire WAR section, which is where that piece of useful info is located. (We just want to build the files to catch refactoring errors at build time instead of runtime.)

**Comment by ChristianMurphy** [comment]
No worries, glad it worked!

**Comment by jimshowalter** [comment]
[ERROR] Failed to execute goal org.jasig.mojo.jspc:jspc-maven-plugin:2.0.2:compile (default-cli) on project webapps-qbo: Execution default-cli of goal org.jasig.mojo.jspc:jspc-maven-plugin:2.0.2:compile failed: basedir C:\dev\qbo\src\qbo\java\src\main\webapp does not exist -> [Help 1]

It seems to think we're building a webapp and into a standard Maven path, but we're not. This is a legacy project (else we wouldn't be using jsp/jspf...), and our directory/package layout looks different.

**Comment by ChristianMurphy** [comment]
That default appears to be coming out of: <https://github.com/Jasig/jspc-maven-plugin/blob/1ea62650f81dfb722f95c0878b8d49ed45e1149e/jspc-maven-plugin/src/main/java/org/codehaus/mojo/jspc/CompilationMojoSupport.java#L78>

It can be overridden with:

``` diff
<plugin>
  <groupId>org.jasig.mojo.jspc</groupId>
  <artifactId>jspc-maven-plugin</artifactId>
  <version>2.0.0</version>
  <configuration>
    <includeInProject>false</includeInProject>
+   <defaultSourcesDirectory>${project.basedir}/some/path</defaultSourcesDirectory>
  </configuration>
  <dependencies>
      <dependency>
          <groupId>org.jasig.mojo.jspc</groupId>
          <artifactId>jspc-compiler-tomcat7</artifactId>
      </dependency>
  </dependencies>
</plugin>
```

**Comment by jimshowalter** [comment]
Fixed, thanks! Now it looks like we'll spend the next week fixing org.apache.jasper.JasperException: The absolute uri cannot be resolved in either web.xml or the jar files deployed with this application, and also missing imports.

**Comment by ChristianMurphy** [comment]
Awesome, I'm going to close out this issue.
If you run into plugin related issues with the web.xml feel free to open up a new ticket.

**Comment by lizgamarra** [comment]
Hi guys, I have a question, is this compatible with openjdk 11? Because I was trying to use the last version and not able to generate always with the same error message: Failed to execute goal org.jasig.mojo.jspc:jspc-maven-plugin:2.0.2:compile (default): Could not find tools.jar
I know that jdk 11 is not containing such jar anymore

**Comment by jgribonvald** [comment]
@lizgamarra nobody made the work for Java 11, so I think it's thée problem that you get. Any contribution is welcome so.
